### ISSUE TITLE
getting 404 github pages after forking the repo 

### ISSUE THREAD

**Issue by 0xbs0d** [jglovier/resume-template#11]
Not sure if I have to configure or add the url after just forking the repo. It works fine offline but on gh pages it displays a 404.

**Comment by jglovier** [comment]
Did you edit the CNAME file (if you are using a custom domain), or remove it (if you are not using a custom domain)?

If you drop a link to your fork I'd be happy to take a look.

**Comment by jglovier** [comment]
Nevermind, I found your fork. Just delete the CNAME file and you should be good.

**Comment by jglovier** [comment]
Also you'll probably want to rename your fork's description and repo link to your URL.

**Comment by 0xbs0d** [comment]
hm... still nothing. deleted the CNAME (silly me) and changed my links in the _config.yml and the description but nothing happened. that should have triggered a rebuild of jekyll afaik.

**Comment by jglovier** [comment]
Well CNAME stuff will take some time to propagate through our DNS servers and CDN, so maybe try again in an hour and lemme know if it's still not working.

**Comment by jglovier** [comment]
Just looked at your repo again. You need to move the code to master. You only use a `gh-pages` branch if your are on a repo that is not named after a user page (i.e. `my-project` uses a `gh-pages` branch, but `username.github.io` uses `master` branch). [Docs on that here](https://help.github.com/articles/user-organization-and-project-pages/).

**Comment by 0xbs0d** [comment]
brilliant! it worked. thank you so much :)

**Comment by jglovier** [comment]
![shaggy-guy-thumbsup](https://cloud.githubusercontent.com/assets/1319791/14740848/ec9653d4-085f-11e6-9333-50805cc80395.gif)
