### ISSUE TITLE
Missing favicon.png

### ISSUE THREAD

**Issue by ghost** [jglovier/resume-template#12]
The favicon.png is missing

**Comment by jglovier** [comment]
I left it out because I thought folks may want to customize it for their use, and I couldn't quite think of a universally appropriate favicon for everyone. Any suggestions for something universal? Or do you think I should just remove it entirely from the code (i.e. the header meta)?

**Comment by ghost** [comment]
Oh, thought it was an oversight since I saw it in code, but not when served. I think either remove from code or add a dummy favicon (that users can change). I personally prefer the latter. Great template btw!

**Comment by jglovier** [comment]
> I think either remove from code or add a dummy favicon (that users can change). I personally prefer the latter. 

@vibinjk25 yeah, agreed. I'll push a fix shortly. Thanks for pointing it out!! :bow:
