### ISSUE TITLE
How to deploy my site on Netlify?

### ISSUE THREAD

**Issue by ghost** [jglovier/resume-template#133]
The default setting can't work, should I add special build command or something else?

**Comment by jglovier** [comment]
Hi @ZihaoFeng2001! 👋  Thanks for reporting this issue. I'm not sure how to help without a little more info.

When you say it can't work, what do you mean? Can you share a screenshot or a code snippet of the error output you are encountering?

**Comment by ghost** [comment]
Thanks for replying to me! I think I have solved this issue. I changed the content in Gemfile and deleted Gemfile.lock, and Netlify and Vercel can deploy the website automatically.

**Comment by jglovier** [comment]
Great! I'm glad to hear you got it sorted out @ZihaoFeng2001. ✨ 🙌 ✨ 

Also, if you have any suggestions for how it could be easier let me know. 😊 (or feel free to open a PR if you'd like to contribute!)
