### ISSUE TITLE
Add pdf export button

### ISSUE THREAD

**Issue by amirj** [jglovier/resume-template#17]
Thank you for this great project. its very useful.
I think the most important and useful feature is pdf export. It's very difficult to sync pdf version with the web-based resume. Do you have any plan to add this feature?

**Comment by jglovier** [comment]
> Do you have any plan to add this feature?

Unfortunately, not at this time. But pull requests welcome! :grin:

**Comment by jglovier** [comment]
There is no simply way to export as a PDF, but @bryanculver added print styles in #22 so it's now possible to get a PDF by printing the rendered resume and choosing the "save to PDF" option available with many browser print dialogs.
