### ISSUE TITLE
Changing fonts

### ISSUE THREAD

**Issue by idontknowanyoneonhere** [jglovier/resume-template#20]
I can't seem to find how to change the fonts for each section. I've found the `font-family` property in `_mixins.scss`  but changing that, changes the font for the whole page, how do i set a different font for only the headings.

Also, when I first forked the repo, i was getting an error on google chrome about a font not serving through https, there's also this `<!-- Google font typography settings - defined in _config.yml -->` in the final html that is served but i can't find these settings anywhere.

Thanks.

**Comment by jibreil** [comment]
I font the Google font settings in `\_includes\head.html` but I

**Comment by idontknowanyoneonhere** [comment]
I figured it out, fonts for headings are on line 54 of `_sass\_mixins.scss` and the font for the rest of the text is on line 78. The _Google Font Typography_ business in `_includes\head.html` is just where you put the code to retrieve the fonts through the Google API. You can see the available fonts [here](https://fonts.google.com/) and it gives you the code, `<link *something* >` goes in `_includes\head.html` and then set the fonts in `_sass\_mixins.scss`.

**Comment by jglovier** [comment]
@jibreil glad you got everything sorted out. Sorry for the delayed response. :grin:
