### ISSUE TITLE
How to add Google Scholar icon link?

### ISSUE THREAD

**Issue by amirj** [jglovier/resume-template#21]
In [this section](https://github.com/jglovier/resume-template/blob/gh-pages/_config.yml#L36-L43), it is possible to add icon links. It's great. But unfortunately, Google Scholar link is not available. Its really important for an academic portfolio. How can I add this link?

**Comment by jglovier** [comment]
@amirj you can just add it there as a config setting in your own fork, and then you can use it as a global variable in your markup in any file. Something like this:

In `_config.yml` you would add:

```
  resume_google_scholar_url:           "http://yoururlgoeshere.com"
```

And then in `_includes/icon-links.html` you would add this:

```
<!-- Website link -->
  {% if site.resume_social_links.resume_google_scholar_url %}
  <li class="icon-link-item"><a href="{{ site.resume_social_links.resume_google_scholar_url }}" class="icon-link" itemprop="url">{% include icons/icon-website.html %}</a></li>
  {% endif %}
```

**Comment by amirj** [comment]
Thank you for your helpful answer.
I just interested to know if anybody have a stylish google scholar svg icon?
Something that is compatible to the set of icons in this project.

**Comment by idontknowanyoneonhere** [comment]
Hi, what's the process for adding custom links and icons? Is it the same as what @jglovier posted earlier?

**Comment by jglovier** [comment]
@amirj I would just suggest using the generic website icon as noted above. I've never seen a social icon for Google Scholar before.

**Comment by jglovier** [comment]
> what's the process for adding custom links and icons?

@jibreil yes, please follow the instructions in my comment above.

**Comment by rmojgani** [comment]
The google scholar SVG file if someone is still interested, also I can commit the other changes necessary

 ` <svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 28 28" enable-background="new 0 0 28 28" xml:space="preserve" width="28">
<path id="Gscholar" fill="#D1CECC" d="M 14 0 A 14 14 0 0 0 0 14 A 14 14 0 0 0 14 28 A 14 14 0 0 0 28 14 A 14 14 0 0 0 14 0 z M 11.367188 4.0976562 L 23.566406 4.0976562 L 22.439453 4.9785156 L 22.439453 6.53125 C 22.858073 6.5850373 22.8125 6.8358539 22.8125 7.1367188 L 22.8125 14.476562 C 22.8125 14.816317 22.535181 15.09375 22.195312 15.09375 L 21.966797 15.09375 C 21.626893 15.09375 21.349609 14.81643 21.349609 14.476562 L 21.349609 7.1367188 C 21.349609 6.8350305 21.306899 6.5842514 21.728516 6.53125 L 21.728516 5.5546875 L 18.482422 8.2167969 C 18.519926 8.2863425 18.554091 8.3303555 18.587891 8.3886719 C 18.873148 8.893532 19.019531 9.5216663 19.019531 10.289062 C 19.019531 10.87728 18.921412 11.406366 18.722656 11.873047 C 18.524837 12.339578 18.284672 12.720181 18.003906 13.013672 C 17.723142 13.308249 17.441707 13.578026 17.160156 13.820312 C 16.878567 14.06316 16.63656 14.315289 16.439453 14.578125 C 16.240809 14.840137 16.142578 15.111814 16.142578 15.392578 C 16.142578 15.673755 16.271508 15.958217 16.527344 16.246094 C 16.782244 16.534797 17.095975 16.815411 17.466797 17.091797 C 17.838295 17.366272 18.207303 17.670396 18.578125 18.001953 C 18.94977 18.3331 19.262679 18.760055 19.517578 19.277344 C 19.774388 19.796575 19.902344 20.367788 19.902344 20.996094 C 19.902344 21.824951 19.690847 22.573975 19.269531 23.240234 C 18.846943 23.903613 18.295619 24.432122 17.619141 24.820312 C 16.940866 25.211122 16.216933 25.506436 15.443359 25.705078 C 14.668178 25.901925 13.89908 26 13.130859 26 C 12.645987 26 12.156047 25.963525 11.664062 25.886719 C 11.170319 25.810061 10.675857 25.673241 10.177734 25.482422 C 9.6786386 25.290366 9.2366521 25.05472 8.8535156 24.771484 C 8.4694049 24.49113 8.160949 24.130082 7.9238281 23.689453 C 7.6867444 23.248674 7.5683594 22.753425 7.5683594 22.203125 C 7.5683594 21.550304 7.7507005 20.943431 8.1152344 20.378906 C 8.4797682 19.818499 8.9618183 19.351179 9.5625 18.980469 C 10.610511 18.328471 12.254341 17.925667 14.492188 17.773438 C 13.980627 17.133903 13.724609 16.532041 13.724609 15.96875 C 13.724609 15.64831 13.808831 15.304416 13.974609 14.933594 C 13.707282 14.970948 13.431268 14.992187 13.150391 14.992188 C 11.948241 14.992188 10.93374 14.601425 10.109375 13.814453 C 9.2850472 13.028866 8.8730469 12.04632 8.8730469 10.857422 C 8.8730469 10.733116 8.8757448 10.623265 8.8847656 10.501953 L 4 10.501953 L 11.367188 4.0976562 z M 13.513672 6.7207031 C 12.747248 6.7207031 12.159974 6.9983778 11.75 7.5488281 C 11.340026 8.0975938 11.134766 8.7618728 11.134766 9.5429688 C 11.134766 10.208255 11.248037 10.885545 11.472656 11.576172 C 11.696452 12.266499 12.060862 12.882593 12.574219 13.425781 C 13.085779 13.970317 13.681056 14.242188 14.357422 14.242188 C 15.111417 14.242188 15.70061 13.989497 16.123047 13.484375 C 16.54369 12.979927 16.755859 12.343156 16.755859 11.576172 C 16.755859 10.922938 16.643606 10.238544 16.419922 9.5234375 C 16.197324 8.8073582 15.825313 8.1611665 15.306641 7.5859375 C 14.789766 7.0087994 14.190861 6.7207031 13.513672 6.7207031 z M 14.78125 18.5 C 14.231361 18.5 13.691256 18.547476 13.160156 18.644531 C 12.62902 18.738967 12.104803 18.899969 11.587891 19.125 C 11.069069 19.348683 10.651125 19.676425 10.332031 20.111328 C 10.011179 20.54567 9.8515625 21.057856 9.8515625 21.646484 C 9.8515625 22.207451 9.9917371 22.708657 10.273438 23.144531 C 10.554202 23.577638 10.923998 23.915355 11.384766 24.158203 C 11.845533 24.401462 12.329686 24.586319 12.833984 24.707031 C 13.339257 24.826959 13.852929 24.888672 14.376953 24.888672 C 15.413324 24.888672 16.306154 24.654181 17.054688 24.1875 C 17.801536 23.720967 18.175781 23.001738 18.175781 22.029297 C 18.175781 21.824777 18.146102 21.622364 18.089844 21.425781 C 18.031117 21.227026 17.972947 21.057278 17.916016 20.916016 C 17.858934 20.777337 17.750269 20.610436 17.589844 20.417969 C 17.430352 20.224939 17.308686 20.083167 17.226562 19.988281 C 17.142794 19.890253 16.986769 19.749395 16.755859 19.564453 C 16.526861 19.378686 16.379471 19.263523 16.314453 19.220703 C 16.250261 19.175675 16.084708 19.052878 15.816406 18.855469 C 15.548256 18.656452 15.400865 18.551526 15.375 18.539062 C 15.234263 18.51361 15.03615 18.5 14.78125 18.5 z "
/>
</svg> `
