### ISSUE TITLE
Bundler Fails due to Eror with ffi package

### ISSUE THREAD

**Issue by colbisaurusrex** [jglovier/resume-template#27]
Not sure what exactly is going on. I don't work with gem or Ruby much. Maybe it's an error on my end. 

![screen shot 2017-04-19 at 11 18 07 am](https://cloud.githubusercontent.com/assets/18058808/25187735/eb89117a-24f1-11e7-8e70-6e623d2317f0.png)

![screen shot 2017-04-19 at 11 18 39 am](https://cloud.githubusercontent.com/assets/18058808/25187755/f9fd389e-24f1-11e7-9403-3870d2e6980f.png)

**Comment by jglovier** [comment]
Hmm, I'm not familiar with this error. What do you get when you try running `gem install ffi -v '1.9.17'` directly?

**Comment by jglovier** [comment]
Closing as stale. If you still have issues, try pulling the latest from the `gh-pages` branch and see if it resolves your issue. If the problem persists further, feel free to reopen this issue.

:v:
