### ISSUE TITLE
Education summary doesn't have clear: both, results in spacing issue

### ISSUE THREAD

**Issue by andreidbr** [jglovier/resume-template#28]
The <p> tag for the Education section's summary doesn't have `style="clear: both;"` like other sections.
As a result, the summary is displayed incorrectly.
Screenshot attached:
![resume_issue](https://cloud.githubusercontent.com/assets/12015956/26026833/9266a918-380b-11e7-9ce5-004df4f1b53c.PNG)

**Comment by jglovier** [comment]
@andreidbr thanks for reporting this! :bow:

**Comment by antgel** [comment]
This is in the `<h5>` tag if I understand correctly, where `{{education.awards}}` goes. Will you be patching this one-liner, or shall I send a PR? :D
