### ISSUE TITLE
Where is your copyright at 2016?

### ISSUE THREAD

**Issue by heldeep** [jglovier/resume-template#30]
I wrote my copyright (at 2017) in my fork, lol

**Comment by jglovier** [comment]
I'm not sure the copyright really serves a purpose for a personal resume like this. The goal of a resume is that you want people to have it, share it, etc. Copyright's are for content that you don't want duplicated anywhere else legally. So I think it's a matter of preference, which makes in your fork perfect, if you feel it improves you version! :zap: 😁
