### ISSUE TITLE
"Outside Interests" section

### ISSUE THREAD

**Issue by antgel** [jglovier/resume-template#32]
I think there should be somewhere to add this - it could render as a simple list of bullets. e.g.
* Astronaut
* Pastry chef
* Heavy metal drummer

Alternatively, it could be a "Miscellaneous" section, but I think that's less structured.

WDYT?

**Comment by jglovier** [comment]
Hey @antgel thanks for opening this up! I know a lot of people do put outside interests on their resume, but for most resumes I don't think it's very appropriate or professional. Granted, it depends on the person, the role, and the industry, so sometimes it's appropriate, but not universally. I'd like to keep this repo focused pretty tightly on the stuff that is universally appropriate for a resume.

**Comment by antgel** [comment]
Hi. It's your project of course, but I'm a little disappointed given that:

1. The flag is there to include it or not.
2. It's very subjective, personally I think it's good to get a taste of the person, not just the worker.
3. One could easily say the same about the image at the top.

**Comment by antgel** [comment]
Adding to the list:
4. Facebook and Instagram links. Arguably universally *inappropriate* for a resume.

**Comment by jglovier** [comment]
>1) the flag is there to include it or not

@antgel I'm sorry, maybe I'm misunderstanding what you are proposing. What are you referring to with a flag that is there to include it? You mean that's how it would work, or are you referring to something already in the project now?

**Comment by jglovier** [comment]
Nm, I see you are referring to your PR and the config option...let's continue this discussion over in the PR. :sparkles:
