### ISSUE TITLE
Update github-pages

### ISSUE THREAD

**Issue by giovannipds** [jglovier/resume-template#39]
Hello. Trying to `bundle` the project today, got an error with `nokogiri 1.7.2`, `nokogiri requires Ruby version < 2.4, >= 2.1.0.` - mine was `2.4.1+`. Looking [here](https://github.com/sparklemotion/nokogiri/issues/1618) I saw that `nokogiri` has already a version supporting my Ruby's version (`1.8.0`), and I fixed it by updating the `bundle` `github-pages`, as mentioned [here](https://github.com/github/pages-gem/#updating).

Can someone update it there?

    bundle update github-pages

I just didn't send an updated `Gemfile.lock` by PR 'cause I'm on Windows, and I don't know if the `x64-mingw32` mentions there will impact anywhere somehow. Cheers, thanks for the repo, good work. =)

**Comment by jglovier** [comment]
Thanks for pointing this out! Fix pushed. :zap:
