### ISSUE TITLE
Question: How can I easily integrate StackExchange "Flair"?

### ISSUE THREAD

**Issue by boldandbusted** [jglovier/resume-template#56]
StackExchange offers "flair" to use on one's own websites. SE gives you HTML to insert in your site like the following:

```
<a href="https://stackexchange.com/users/2828272/jesse-adelman"><img src="https://stackexchange.com/users/flair/2828272.png" width="208" height="58" alt="profile for Jesse Adelman on Stack Exchange, a network of free, community-driven Q&amp;A sites" title="profile for Jesse Adelman on Stack Exchange, a network of free, community-driven Q&amp;A sites" /></a>
```

What's a decent, maintainable method for including such a nice thing within this excellent resume template? :D And, a bonus would be to NOT show it if for some reason the URI becomes invalid.  Thanks in advance.

**Comment by Minimalistic** [comment]
I haven't any experience on the matter, but perhaps [se-flair](https://stackapps.com/questions/2119/se-flair-html-combined-stack-exchange-site-flair) could be tapped into for what you're looking to do?

**Comment by jglovier** [comment]
This resume template wasn't designed to support embedded content, but you could certainly add it to your own fork by simply putting the markup wherever you'd like it to appear.
