### ISSUE TITLE
resume header contact info?

### ISSUE THREAD

**Issue by frankiezeager** [jglovier/resume-template#62]
My resume header contact info (phone number, address, etc) doesn't show up in the resume after assigning it in _config.yml, and it also doesn't appear to be in the template example either. Any way to get it to display?

**Comment by jglovier** [comment]
@frankiezeager you're right! Good catch.

It was added in #42 to improve schema data, but never actually put into the template as rendered output anywhere. 🙈 

I'll open a PR to resolve that.

**Comment by jglovier** [comment]
@frankiezeager so I just realized you can accomplish what you're after by removing the `print-only` class from the `header-contact-info` element in [`_layouts/resume.html`](https://github.com/jglovier/resume-template/blob/gh-pages/_layouts/resume.html#L23).

However, I've also opened #63 to make this a bit simpler so with that update you'd be able to simply change the `display_header_contact_info` value in `_config.yml` to true to display the info on the page.

Thanks for the feedback!
