### ISSUE TITLE
Unable to access the website

### ISSUE THREAD

**Issue by rs9899** [jglovier/resume-template#89]
http://resume-template.joelglovier.com
`This site can’t be reached`
`resume-template.joelglovier.com’s`
`server IP address could not be found.`
`DNS_PROBE_FINISHED_NXDOMAIN`

**Comment by jglovier** [comment]
@rs9899 thanks for the heads up! 🙇

**Comment by jglovier** [comment]
Fixed! ✨

**Comment by rs9899** [comment]
Thanks
